### ISSUE TITLE
Installation Howto

### ISSUE THREAD

**Issue by dbonomo** [zenman/zemplate#6]
Hey guys, cool template! I'm trying to get grunt to work on my system, and although this is actually probably a grunt-contrib-compass problem, I thought I'd ask if you folks have a slick way of getting rid of the "You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue." Problem I've run into. I've tried "gem update --system && gem install compass", npm installing grunt-contrib-compass, and a few other things but I can't seem to make it work. How does the Zenman folks get compass installed in system PATH? Thanks!

**Comment by ryansalerno** [comment]
I'm sorry no one got back to you on this....

I'm going to close this issue as we're launching a new version imminently and neither Grunt nor Compass have made it in.

**Comment by dbonomo** [comment]
No worries! I'm looking forward to seeing the new one when it rolls out. Sounds like you're going to open-source the core again?

**Comment by ryansalerno** [comment]
It's very kind of you to give us another chance.

I'm waiting to merge into master until I get at least some of the utility classes documented better, but you can check it out here: https://github.com/zenman/zemplate/tree/4.0.0

We've already built a couple sites with it in various forms of pre-release, and I expect we'll push tweaks pretty regularly but it's a pretty nice base for us.... (Plus I'll be here for any support you need or feedback you have this time.)
